### ISSUE TITLE
ToggleVisibility Bug

### ISSUE THREAD

**Issue by lennier83** [1up-lab/contao-points-of-interest#15]
Contao: 4.13LTS
Neueser Pull of POI

Kurze Frage: Es ist zwar offiziell nur für Contao 4.9 verfügbar, aber falls Ihr auf die schnelle seht warum das Offline/Online schalten nicht klappt einzelner POIs, wäre das Knorke. Es  sind immer alle online, auch wenn ausgestellt. Fehlermeldungen gibt es soweit nicht.
Sehe den Fehler bei dem Visibility-Toggle auch nicht im Code.
Ansonsten sehr schöne Erweiterung :-D

**Comment by bytehead** [comment]
Kannst du in deiner `composer.json` mal testweise den Branch `dev-fix/visibility as 2.2.1` anstatt der `2.2.0` requiren und prüfen ob die Version das Problem löst?

**Comment by bytehead** [comment]
Danke fürs testen. Ich veröffentliche gerade noch eine neue Version, `^2.2.1` sollte dann in deiner `composer.json` wieder stehen :)

**Comment by bytehead** [comment]
https://github.com/1up-lab/contao-points-of-interest/releases/tag/2.2.1 🥳
