### ISSUE TITLE
Öffnen in Colorbox?

### ISSUE THREAD

**Issue by tblumrich** [1up-lab/contao-points-of-interest#17]
Hallo!
Ich hab nichts dazu gefunden, aber ist es so gedacht, das sich angeklickte POIs in der Colorbox öffnen (JS, CSS nutzen ist angehakt)? Aufgrund der angegebenen Quelle dachte ich das wird so wie bei https://codyhouse.co/gem/points-of-interest/ und die Öffnungen erfolgen in einem eigenen Modal.
Ich habe dabei das Problem, das der eingestellte Text (nur Text als Textelement) viel breiter als der Viewport wird und ich nirgends (scheinbar) Einfluss nehmen kann (ausser CSS natürlich)
Alternativ eingestellte Lightboxen (z.b. Glightbox) werden garnicht verarbeitet.

Muss ich noch irgendwo etwas einstellen? Ist ein aktuelles Contao 4.13 unter PHP 8.0.26 und die Extension ist 2.2.1

Danke vorab, Thomas :)

**Comment by bytehead** [comment]
Die POIs müssten sich eigentlich schon in der Colorbox öffnen lassen (sofern kein Link hinterlegt) - das sagt jedenfalls der Code.

https://github.com/1up-lab/contao-points-of-interest/blob/f7e0a89d0fc5279f97fe0e7ee9f58f120b4adf9f/src/Resources/public/js/poi.js#L18-L21

Hast du einen Link zur Seite mit dem Problem? Oder wie sieht der generierte Sourcecode der POIs aus?

**Comment by tblumrich** [comment]
Danke für die Rückmeldung.
Ja, die Colorbox öffnet sich - inzwischen durch CSS auch erträglich vom Design.

Das heißt die Extension funktioniert ausschließlich mit der Colorbox? Wenn ich eine alternative Extension js_ oder j_ (z.B. https://packagist.org/packages/inspiredminds/contao-glightbox) welche die Colorbox ersetzen soll z.B. für Galerien usw. installiere funktioniert die Öffnung der POIs nicht.

Des weiteren hatte ich eigentlich erwartet, das die Erweiterung eine eigene Modalfunktionalität mitbringt, wie hier: https://codyhouse.co/demo/points-of-interest/index.html
Ist ja etwas eleganter, da sich das Modal direkt am POI öffnet. Die Colorbox öffnet das ja immer einfach über der POI Grafik als mittiges Overlay und verdeckt dann in der Regel die POIs. [Beispiel](http://ragross.blusi.de/ueber-uns.html)

Müsste man sich wohl selbst programmieren bzw. programmieren lassen?

**Comment by bytehead** [comment]
Es ist mir unmöglich, die Extension mit allem möglichen an sonstigen Extensions kompatibel zu machen. Insofern steht dir offen, das CSS und JS auf deinen Anwendungsbereich zuzuschneiden und auf die entsprechend eingesetzten Libraries anzupassen (das HTML-Markup lässt sich über die Templates anpassen).

**Comment by lennier83** [comment]
Da die colorbox zu contao gehört, is es natürlich logisch das mit Contao onBoard zu verknüpfen denke ich. Also alles out-of-box zu machen.
Tatsächlich ist die Erweiterung mächtiger als man denken könnte mit wenig Anpassungen. Ob Ajax inhalte oder mit https://popper.js.org/ .... alles machbar :-)
Empfehle popper damit man die tooltip-popups wie in der Demo nicht manuell anpassen muss wie sie fließen. Einfach poi mit dem script ergänzen und Redakteure freuen sich.

**Comment by bytehead** [comment]
Die Extension könnte auch zwei Varianten anbieten - je nach Geschmack und Menge des Contents - Colourbox oder Popper.js. :)
