### ISSUE TITLE
Contao 4.11.3 issue while using

### ISSUE THREAD

**Issue by Ukgcity** [1up-lab/contao-points-of-interest#9]
Contao 4.11.3

Issue in /var/logs/

`request.CRITICAL: Uncaught PHP Exception LogicException: ""contao.fragment._contao.frontend_module.points_of_interest" has no container set, did you forget to define it as a service subscriber?" at /var/www/vhosts/bauconsulting-eberl.at/httpdocs-thermosockel/vendor/symfony/framework-bundle/Controller/ControllerResolver.php line 39 {"exception":"[object] (LogicException(code: 0): \"contao.fragment._contao.frontend_module.points_of_interest\" has no container set, did you forget to define it as a service subscriber? at /var/www/vhosts/bauconsulting-eberl.at/httpdocs-thermosockel/vendor/symfony/framework-bundle/Controller/ControllerResolver.php:39)"} []`

Googling gave only [that](https://github.com/terminal42/contao-pageimage/issues/46)

**Comment by bytehead** [comment]
Have you tried to require `symfony/framework-bundle` in version `4.4.*`?

**Comment by Ukgcity** [comment]
> Have you tried to require `symfony/framework-bundle` in version `4.4.*`?

Did you mean, add it to composer.json?

**Comment by bytehead** [comment]
yes! :) The error comes because of the `symfony/framework-bundle` in version `5.x` as far as I cann see this in https://github.com/terminal42/contao-pageimage/issues/46.
